"""add utility_connections table

Revision ID: 099bd4eb5beb
Revises: b467ce910120
Create Date: 2026-06-11 10:49:51.493146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099bd4eb5beb'
down_revision: Union[str, None] = 'b467ce910120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('utility_type', sa.String(length=50), nullable=False),
    sa.Column('utility_provider', sa.String(length=255), nullable=True),
    sa.Column('consumer_number', sa.String(length=100), nullable=True),
    sa.Column('meter_number', sa.String(length=100), nullable=True),
    sa.Column('tariff_category', sa.String(length=100), nullable=True),
    sa.Column('supply_voltage', sa.String(length=20), nullable=True),
    sa.Column('sanctioned_load', sa.String(length=50), nullable=True),
    sa.Column('first_bill_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_bill_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_document_id', sa.UUID(), nullable=True),
    sa.Column('billing_cycle_months', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'utility_type', 'consumer_number', name='uq_facility_utility_consumer')
    )
    op.create_index(op.f('ix_utility_connections_company_id'), 'utility_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_utility_connections_facility_id'), 'utility_connections', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_connections_facility_id'), table_name='utility_connections')
    op.drop_index(op.f('ix_utility_connections_company_id'), table_name='utility_connections')
    op.drop_table('utility_connections')
    # ### end Alembic commands ###
