"""create all core ESG tables

Revision ID: 5b9ec68d782f
Revises: 0a9c59ace805
Create Date: 2026-06-07 15:39:38.720735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9ec68d782f'
down_revision: Union[str, None] = '0a9c59ace805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('ELECTRICITY_BILL', 'FUEL_RECEIPT', 'WATER_BILL', 'WATER_QUALITY_REPORT', 'GENERATOR_LOG', 'VEHICLE_LOG', 'REFRIGERANT_LOG', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_facility_id'), 'documents', ['facility_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('emission_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('activity_table', sa.String(length=100), nullable=True),
    sa.Column('activity_data', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('activity_unit', sa.String(length=20), nullable=False),
    sa.Column('emission_factor', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('ef_source', sa.String(length=100), nullable=True),
    sa.Column('ef_unit', sa.String(length=50), nullable=True),
    sa.Column('co2e_kg', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('co2_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ch4_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('n2o_kg', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_records_company_id'), 'emission_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_emission_records_facility_id'), 'emission_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emission_records_period_start'), 'emission_records', ['period_start'], unique=False)
    op.create_table('energy_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('energy_source', sa.Enum('ELECTRICITY', 'DIESEL', 'LPG', 'CNG', 'FURNACE_OIL', 'COAL', 'BIOMASS', 'SOLAR', 'OTHER', name='energysource'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.Enum('KWH', 'LITRES', 'KG', 'MMBTU', 'GJ', name='energyunit'), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reading_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meter_number', sa.String(length=100), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('entry_method', sa.Enum('DOCUMENT_EXTRACTION', 'MANUAL', 'API_INTEGRATION', 'CSV_UPLOAD', name='dataentrymethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_activities_company_id'), 'energy_activities', ['company_id'], unique=False)
    op.create_index(op.f('ix_energy_activities_facility_id'), 'energy_activities', ['facility_id'], unique=False)
    op.create_index(op.f('ix_energy_activities_period_start'), 'energy_activities', ['period_start'], unique=False)
    op.create_table('water_quality_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('sample_id', sa.String(length=100), nullable=True),
    sa.Column('water_type', sa.Enum('DRINKING', 'PROCESS', 'WASTEWATER', 'GROUNDWATER', 'SURFACE_WATER', 'TREATED_EFFLUENT', name='watertype'), nullable=False),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_desc', sa.String(length=255), nullable=True),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('lab_report_ref', sa.String(length=100), nullable=True),
    sa.Column('overall_status', sa.Enum('SAFE', 'EXCEEDS_LIMIT', 'NO_LIMIT', 'NO_DATA', name='compliancestatus'), nullable=True),
    sa.Column('parameters_safe', sa.Numeric(precision=5, scale=0), nullable=True),
    sa.Column('parameters_exceeded', sa.Numeric(precision=5, scale=0), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_quality_samples_collection_date'), 'water_quality_samples', ['collection_date'], unique=False)
    op.create_index(op.f('ix_water_quality_samples_company_id'), 'water_quality_samples', ['company_id'], unique=False)
    op.create_index(op.f('ix_water_quality_samples_facility_id'), 'water_quality_samples', ['facility_id'], unique=False)
    op.create_table('water_quantity_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('water_source', sa.Enum('MUNICIPAL', 'GROUNDWATER', 'RAINWATER', 'SURFACE_WATER', 'RECYCLED', 'TANKER', 'OTHER', name='watersource'), nullable=False),
    sa.Column('water_category', sa.Enum('WITHDRAWAL', 'CONSUMPTION', 'RECYCLED', 'DISCHARGED', name='watercategory'), nullable=False),
    sa.Column('quantity_kl', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meter_number', sa.String(length=100), nullable=True),
    sa.Column('entry_method', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_quantity_records_company_id'), 'water_quantity_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_water_quantity_records_facility_id'), 'water_quantity_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_water_quantity_records_period_start'), 'water_quantity_records', ['period_start'], unique=False)
    op.create_table('water_quality_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('is_estimated', sa.String(length=5), nullable=False),
    sa.Column('who_limit', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('bis_limit', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cpcb_limit', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('epa_limit', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('compliance_status', sa.Enum('SAFE', 'EXCEEDS_LIMIT', 'NO_LIMIT', 'NO_DATA', name='compliancestatus'), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['water_quality_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_quality_readings_company_id'), 'water_quality_readings', ['company_id'], unique=False)
    op.create_index(op.f('ix_water_quality_readings_sample_id'), 'water_quality_readings', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_quality_readings_sample_id'), table_name='water_quality_readings')
    op.drop_index(op.f('ix_water_quality_readings_company_id'), table_name='water_quality_readings')
    op.drop_table('water_quality_readings')
    op.drop_index(op.f('ix_water_quantity_records_period_start'), table_name='water_quantity_records')
    op.drop_index(op.f('ix_water_quantity_records_facility_id'), table_name='water_quantity_records')
    op.drop_index(op.f('ix_water_quantity_records_company_id'), table_name='water_quantity_records')
    op.drop_table('water_quantity_records')
    op.drop_index(op.f('ix_water_quality_samples_facility_id'), table_name='water_quality_samples')
    op.drop_index(op.f('ix_water_quality_samples_company_id'), table_name='water_quality_samples')
    op.drop_index(op.f('ix_water_quality_samples_collection_date'), table_name='water_quality_samples')
    op.drop_table('water_quality_samples')
    op.drop_index(op.f('ix_energy_activities_period_start'), table_name='energy_activities')
    op.drop_index(op.f('ix_energy_activities_facility_id'), table_name='energy_activities')
    op.drop_index(op.f('ix_energy_activities_company_id'), table_name='energy_activities')
    op.drop_table('energy_activities')
    op.drop_index(op.f('ix_emission_records_period_start'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_facility_id'), table_name='emission_records')
    op.drop_index(op.f('ix_emission_records_company_id'), table_name='emission_records')
    op.drop_table('emission_records')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_facility_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
