"""add production_records table

Revision ID: b27068d90abd
Revises: 099bd4eb5beb
Create Date: 2026-06-13 16:40:50.975957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27068d90abd'
down_revision: Union[str, None] = '099bd4eb5beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('period_label', sa.String(length=7), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('is_estimated', sa.String(length=5), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_company_id'), 'production_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_production_records_facility_id'), 'production_records', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_records_facility_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_company_id'), table_name='production_records')
    op.drop_table('production_records')
    # ### end Alembic commands ###
