"""add consultant_clients table

Revision ID: b467ce910120
Revises: f72f9d529da7
Create Date: 2026-06-10 21:00:04.703415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b467ce910120'
down_revision: Union[str, None] = 'f72f9d529da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultant_id', sa.UUID(), nullable=False),
    sa.Column('client_company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consultant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultant_id', 'client_company_id', name='uq_consultant_client')
    )
    op.create_index(op.f('ix_consultant_clients_client_company_id'), 'consultant_clients', ['client_company_id'], unique=False)
    op.create_index(op.f('ix_consultant_clients_consultant_id'), 'consultant_clients', ['consultant_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('BRSR', 'INVESTOR_ESG', 'CSR_FUNDING', 'WATER_QUALITY', 'CARBON_SUMMARY', name='reporttype'), nullable=False),
    sa.Column('report_format', sa.Enum('PDF', 'EXCEL', 'JSON', name='reportformat'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_seconds', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_company_id'), 'reports', ['company_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_company_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_consultant_clients_consultant_id'), table_name='consultant_clients')
    op.drop_index(op.f('ix_consultant_clients_client_company_id'), table_name='consultant_clients')
    op.drop_table('consultant_clients')
    # ### end Alembic commands ###
